# Generated by Django 4.0.4 on 2022-05-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedrace',
            name='raw',
            field=models.JSONField(default=dict),
        ),
    ]
