# Generated by Django 4.0.4 on 2022-05-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_scrapedrace_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedrace',
            name='start',
        ),
        migrations.AddField(
            model_name='scrapedrace',
            name='start_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scrapedrace',
            name='start_time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
